name: Deploy to GitHub pages.

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree dist add --all
      - run: git commit -m "Automated deployment to GitHub Pages"
      - run: git push origin HEAD:gh-pages --force
